-- Booking & order domain — Phase 4.4.
--
-- This is the transaction architecture underneath a future checkout, not
-- checkout itself: no booking-creation UI, no payment gateway, no webhook
-- handler exists yet (all explicitly out of scope this phase). What this
-- migration establishes is the durable record a future booking flow will
-- write to, and the database-side guarantee that two concurrent booking
-- attempts against the same departure can never both take the last seat.
--
-- Five things are kept deliberately separate, matching this phase's own
-- brief exactly — content (trips, already Phase 4.1), commercial
-- inventory (trip_departures, already Phase 4.1), booking (this file),
-- payment (this file), and traveller identity (not built yet — see
-- `bookings.traveller_id`'s own comment):
--
--   trips / trip_departures  -- WHAT the trip is, WHEN it departs (Phase 4.1)
--   bookings                 -- a traveller's reservation against one departure
--   booking_participants     -- who is actually travelling on it
--   payments                 -- money moved against a booking
--
-- Reconciling this against docs/DATABASE.md §4/§12's original sketch
-- (`user_id`, `subtotal`/`discount_amount`/`total_amount`/`amount_paid`/
-- `amount_due`, `payment_installments`, `coupons`, `refunds`, and a six-state
-- DRAFT/PENDING_PAYMENT/CONFIRMED/PARTIALLY_PAID/BALANCE_DUE/COMPLETED
-- booking lifecycle): that sketch is the FULL future vision
-- (docs/ROADMAP.md Phase 6 — booking & payments). This phase deliberately
-- implements a narrower, real subset — a single `price_amount` rather than
-- subtotal/discount/total (no coupons exist to discount against yet), one
-- `pending -> confirmed -> completed` happy path plus `cancelled` (no
-- partial-payment or refund states — a future phase's job, once
-- instalments/refunds are real features, not before) — documented in
-- docs/DATABASE.md as an intentional narrowing, not an oversight.

-- ============================================================= bookings --

-- The four-state model this phase actually needs, not the richer one
-- docs/DATABASE.md sketches for a future phase (see this file's header):
--
--   pending    a reservation exists; payment has not yet succeeded
--   confirmed  payment succeeded in full
--   cancelled  withdrawn, by the traveller or an operator, before or after
--              confirmation — refund handling (if any) lives on `payments`,
--              a future `refunded` payment status, not a new booking status
--   completed  the departure has concluded
--
-- Valid transitions (enforced below by `bookings_validate_status_transition`,
-- not left to application discipline alone, since no booking-write
-- application layer exists yet this phase to enforce it instead):
--
--   pending   -> confirmed  (a future payment-success handler)
--   pending   -> cancelled  (traveller or operator, before payment)
--   confirmed -> cancelled  (operator, after payment — refund is a
--                            separate, future concern)
--   confirmed -> completed  (a future scheduled job, once the departure
--                            date has passed)
--
-- No transition out of `cancelled` or `completed` — both are terminal.
create table public.bookings (
  id uuid primary key default gen_random_uuid(),

  -- Human-readable, customer-facing — never the UUID above. Generated by
  -- `bookings_generate_reference` below when left null on insert; the
  -- unique constraint is the actual backstop, not the generator's own
  -- (already very low) collision odds.
  reference text not null unique,

  trip_departure_id uuid not null references public.trip_departures (id),

  -- Nullable: the traveller-authentication system this would reference
  -- does not exist yet (Phase 4.5+). A booking must be representable
  -- before it does — see `contact_name`/`contact_email`/`contact_phone`
  -- below for how a booking identifies who made it in the meantime. Once
  -- real traveller accounts exist, this column starts getting populated;
  -- it is not renamed or restructured to make that possible; ON DELETE
  -- SET NULL rather than CASCADE — a traveller account being removed must
  -- never silently delete the historical fact that a booking happened.
  traveller_id uuid references auth.users (id) on delete set null,

  -- The minimum contact identity a booking needs when there is no
  -- traveller account behind it yet (or ever, for a guest booking) — not
  -- a parallel account system, just enough to reach the person who booked.
  contact_name text not null check (btrim(contact_name) <> ''),
  contact_email text not null check (btrim(contact_email) <> ''),
  contact_phone text check (contact_phone is null or btrim(contact_phone) <> ''),

  -- How many seats this booking holds against the departure's capacity —
  -- the figure `bookings_reserve_seats` (below) actually reserves.
  -- `booking_participants` is the human-readable roster; this column is
  -- the source of truth for capacity arithmetic, checked at insert time
  -- when participants may not exist as rows yet. Keeping them in sync is
  -- an application-layer invariant once a booking-write flow exists
  -- (documented in docs/DATABASE.md), not something a CHECK constraint
  -- can express across two tables.
  participant_count integer not null check (participant_count > 0),

  status text not null default 'pending' check (
    status in ('pending', 'confirmed', 'cancelled', 'completed')
  ),

  -- ---- Commercial snapshot -------------------------------------------
  -- The commercial facts of THIS transaction, fixed at booking time —
  -- never re-read from `trips`/`trip_departures` for historical display,
  -- so a later content edit or price change cannot silently rewrite what
  -- a traveller actually bought (this phase's own "content immutability
  -- boundary" requirement). Deliberately NOT the entire trip row: an
  -- itinerary correction, a new host, or a reworded FAQ has no commercial
  -- meaning for an existing booking and does not belong in it. Each field
  -- below is one specific fact a receipt or a support conversation would
  -- need to state confidently regardless of what `trips`/`trip_departures`
  -- say today:
  snapshot_trip_title text not null check (btrim(snapshot_trip_title) <> ''),
  snapshot_trip_slug text not null check (btrim(snapshot_trip_slug) <> ''),
  snapshot_destination text not null check (btrim(snapshot_destination) <> ''),
  snapshot_departure_date date not null,
  snapshot_return_date date,
  snapshot_price_amount numeric(12, 2) not null check (snapshot_price_amount > 0),
  snapshot_price_currency char(3) not null check (snapshot_price_currency ~ '^[A-Z]{3}$'),

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint bookings_snapshot_return_after_departure check (
    snapshot_return_date is null or snapshot_return_date >= snapshot_departure_date
  )
);

create index bookings_trip_departure_id_idx on public.bookings (trip_departure_id);
create index bookings_traveller_id_idx on public.bookings (traveller_id) where traveller_id is not null;
create index bookings_status_idx on public.bookings (status);

create trigger bookings_set_updated_at
  before update on public.bookings
  for each row
  execute function public.set_updated_at();

-- ------------------------------------------------- reference generation --

-- "WWS-" + 8 unambiguous base32-style characters (no 0/O/1/I) — customer-
-- facing, so visually confusable characters are excluded deliberately, not
-- an oversight. Never called with an argument; exists as its own function
-- (rather than inlined into the trigger below) so the format is documented
-- and testable in one place.
create function public.generate_booking_reference()
returns text
language plpgsql
as $$
declare
  alphabet text := 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  suffix text := '';
begin
  for i in 1..8 loop
    suffix := suffix || substr(alphabet, 1 + floor(random() * length(alphabet))::int, 1);
  end loop;
  return 'WWS-' || suffix;
end;
$$;

-- Generates a reference only when the caller left it null, retrying on the
-- astronomically unlikely collision rather than trusting the generator's
-- odds alone — the table's own `unique` constraint is the real backstop;
-- this loop just avoids surfacing a raw constraint-violation error for
-- what is almost always a one-in-first-try success.
create function public.bookings_assign_reference()
returns trigger
language plpgsql
as $$
declare
  candidate text;
  attempts int := 0;
begin
  if new.reference is not null then
    return new;
  end if;

  loop
    candidate := public.generate_booking_reference();
    attempts := attempts + 1;
    if not exists (select 1 from public.bookings where reference = candidate) then
      new.reference := candidate;
      return new;
    end if;
    if attempts >= 10 then
      raise exception 'Could not generate a unique booking reference after % attempts', attempts;
    end if;
  end loop;
end;
$$;

create trigger bookings_assign_reference_trigger
  before insert on public.bookings
  for each row
  execute function public.bookings_assign_reference();

-- ---------------------------------------------- seat reservation boundary --

-- The atomic primitive this phase's "concurrency" requirement is actually
-- about: a single `UPDATE ... WHERE ... RETURNING` is one statement, so
-- Postgres takes the row lock on `trip_departures` for the duration of the
-- capacity check AND the increment — two concurrent bookings against the
-- last seat serialize on that lock, and the second one's WHERE clause
-- re-evaluates `seats_reserved` after the first has already committed its
-- increment, so it correctly sees no capacity left. No application-level
-- read-then-write race is possible here; nothing in JavaScript ever adds
-- to `seats_reserved` directly (docs/SECURITY.md's "never trust the client
-- for availability" applies to the SERVER's own arithmetic too, not only
-- the browser's).
create function public.bookings_reserve_seats(p_departure_id uuid, p_seats integer)
returns void
language plpgsql
as $$
begin
  update public.trip_departures
  set seats_reserved = seats_reserved + p_seats
  where id = p_departure_id
    and (capacity is null or seats_reserved + p_seats <= capacity);

  if not found then
    raise exception 'Not enough capacity on departure % for % seat(s)', p_departure_id, p_seats;
  end if;
end;
$$;

-- The inverse — a cancelled booking gives its seats back. `p_from_confirmed`
-- also releases the matching `seats_confirmed` count (a confirmed seat is
-- also a reserved seat — trip_departures_confirmed_within_reserved — so
-- cancelling a confirmed booking must release both).
create function public.bookings_release_seats(
  p_departure_id uuid,
  p_seats integer,
  p_from_confirmed boolean
)
returns void
language plpgsql
as $$
begin
  update public.trip_departures
  set
    seats_reserved = greatest(seats_reserved - p_seats, 0),
    seats_confirmed = case
      when p_from_confirmed then greatest(seats_confirmed - p_seats, 0)
      else seats_confirmed
    end
  where id = p_departure_id;
end;
$$;

create function public.bookings_confirm_seats(p_departure_id uuid, p_seats integer)
returns void
language plpgsql
as $$
begin
  update public.trip_departures
  set seats_confirmed = seats_confirmed + p_seats
  where id = p_departure_id;
end;
$$;

-- A new booking always starts `pending` (never trust an insert claiming
-- otherwise — "do not automatically confirm bookings just because a
-- payment-intent-like record exists") and must reserve its seats in the
-- SAME transaction as its own insert: raising here aborts the whole
-- INSERT, so a booking row can never exist without the capacity that
-- justified it actually having been reserved.
create function public.bookings_before_insert()
returns trigger
language plpgsql
as $$
begin
  if new.status is distinct from 'pending' then
    raise exception 'New bookings must start pending, not "%"', new.status;
  end if;

  perform public.bookings_reserve_seats(new.trip_departure_id, new.participant_count);
  return new;
end;
$$;

create trigger bookings_before_insert_trigger
  before insert on public.bookings
  for each row
  execute function public.bookings_before_insert();

-- Mirrors `lib/booking/status.ts`'s transition table exactly (see that
-- file) — kept in two places for the same reason
-- `lib/content/ingest/schema.ts`'s Zod shapes mirror this project's DB
-- CHECK constraints: no application write-layer exists yet to enforce
-- this instead, so the database is the only real enforcement point today.
create function public.booking_status_transition_is_valid(p_from text, p_to text)
returns boolean
language sql
immutable
as $$
  select (p_from, p_to) in (
    ('pending', 'confirmed'),
    ('pending', 'cancelled'),
    ('confirmed', 'cancelled'),
    ('confirmed', 'completed')
  );
$$;

create function public.bookings_before_update()
returns trigger
language plpgsql
as $$
begin
  if new.status is distinct from old.status then
    if not public.booking_status_transition_is_valid(old.status, new.status) then
      raise exception 'Invalid booking status transition: % -> %', old.status, new.status;
    end if;

    if new.status = 'cancelled' then
      perform public.bookings_release_seats(
        old.trip_departure_id,
        old.participant_count,
        old.status = 'confirmed'
      );
    elsif new.status = 'confirmed' then
      perform public.bookings_confirm_seats(old.trip_departure_id, old.participant_count);
    end if;
  end if;

  return new;
end;
$$;

create trigger bookings_before_update_trigger
  before update on public.bookings
  for each row
  execute function public.bookings_before_update();

-- A hard delete is not a normal business operation (cancellation is —
-- `status = 'cancelled'` above, which keeps the historical row) but the
-- seats a deleted booking held must not stay reserved forever just
-- because the row disappeared instead of being cancelled first — a data
-- correction, or this project's own tests cleaning up after themselves,
-- must leave `trip_departures` exactly as if the booking had never
-- existed.
create function public.bookings_before_delete()
returns trigger
language plpgsql
as $$
begin
  perform public.bookings_release_seats(
    old.trip_departure_id,
    old.participant_count,
    old.status = 'confirmed'
  );
  return old;
end;
$$;

create trigger bookings_before_delete_trigger
  before delete on public.bookings
  for each row
  execute function public.bookings_before_delete();

-- ==================================================== booking_participants --

-- The human roster a booking represents — deliberately separate from
-- `bookings` itself so "one booking, several travellers" needs no
-- duplicated booking rows (this phase's own "do not assume one booking =
-- one traveller" requirement). Intentionally minimal: no passport, no
-- government ID, no date of birth, no medical information — none of
-- which this phase (or any confirmed WWS requirement) has an established
-- need for yet (docs/SECURITY.md's "collect only information needed").
create table public.booking_participants (
  id uuid primary key default gen_random_uuid(),
  booking_id uuid not null references public.bookings (id) on delete cascade,
  full_name text not null check (btrim(full_name) <> ''),
  -- Exactly one participant per booking is its point of contact — not
  -- necessarily the same person as `bookings.contact_*` (a parent could
  -- book and travel with their child as the "lead" traveller on the
  -- ground), so this is its own flag, not inferred from row order.
  is_lead boolean not null default false,
  created_at timestamptz not null default now()
);

create index booking_participants_booking_id_idx on public.booking_participants (booking_id);
create unique index booking_participants_one_lead_per_booking
  on public.booking_participants (booking_id)
  where is_lead;

-- ================================================================ payments --

-- Distinguishable from `bookings` on purpose (this phase's own
-- requirement) — a booking can exist while zero, one, or (once retries/
-- partial payments are real features) more than one payment record exists
-- against it. No payment provider is hardcoded (`provider` is free text,
-- not an enum): the model must not assume Razorpay, Stripe, or any other
-- specific gateway, matching "do not hardcode a single payment provider
-- into the data model."
create table public.payments (
  id uuid primary key default gen_random_uuid(),
  booking_id uuid not null references public.bookings (id),

  provider text not null check (btrim(provider) <> ''),
  -- Nullable: a payment attempt may exist before the provider has assigned
  -- its own reference (e.g. a locally-created "payment intent" row created
  -- just before redirecting to a gateway — a future concern, not built
  -- this phase, but the column must not force a fake placeholder value to
  -- satisfy a NOT NULL constraint it doesn't yet have a real value for).
  provider_reference text,

  amount numeric(12, 2) not null check (amount > 0),
  currency char(3) not null check (currency ~ '^[A-Z]{3}$'),

  status text not null default 'pending' check (
    status in ('pending', 'succeeded', 'failed', 'refunded')
  ),

  -- Set once, when the provider confirms funds actually settled — distinct
  -- from `created_at` (when WWS first recorded the attempt) and from
  -- `status` turning 'succeeded' at the provider's own event time, which a
  -- retried/out-of-order webhook could in principle report before this
  -- row's insert finishes committing.
  captured_at timestamptz,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index payments_booking_id_idx on public.payments (booking_id);

-- Webhook safety: a provider may retry or reorder delivery of the same
-- event. A partial unique index (not a plain `unique(provider,
-- provider_reference)` column constraint) so multiple payment attempts
-- that never got a provider reference at all (still null) don't collide
-- with each other, while any attempt that DID get one is guaranteed
-- unique — the exact shape idempotent webhook processing needs later
-- (not built this phase): "insert this event's row, and let the unique
-- index itself reject a duplicate delivery" rather than a hand-rolled
-- has-this-event-been-seen check.
create unique index payments_provider_reference_unique
  on public.payments (provider, provider_reference)
  where provider_reference is not null;

create trigger payments_set_updated_at
  before update on public.payments
  for each row
  execute function public.set_updated_at();

-- ===================================================================== RLS --

-- No `anon` or `authenticated` policy of any kind on any of the three
-- tables above — not even a self-read policy. This is deliberate, not an
-- oversight this phase forgot to close:
--
--   - No traveller-authentication architecture exists yet to scope a
--     "read your own bookings" policy against (`bookings.traveller_id` is
--     null for every row today) — writing that policy now, against an
--     identity system that doesn't exist, would be exactly the kind of
--     premature, untestable RLS this project's own conventions warn
--     against.
--   - No admin booking-management UI exists yet either (explicitly out of
--     scope this phase) to justify an "admins can read every booking"
--     policy the way Phase 4.3 added for trip content — adding one with
--     nothing to consume it would be a table getting a feature merely
--     because it is possible.
--
-- Every current and near-future access path is therefore the service-role
-- client only, after an application-layer authorization check — exactly
-- Phase 4.3's `lib/admin/` pattern, which a future booking-operations
-- surface would reuse rather than reinvent. RLS stays enabled (never
-- disabled) on all three tables regardless, so the moment a real policy is
-- added it takes effect immediately with no separate migration step to
-- "turn RLS on."
alter table public.bookings enable row level security;
alter table public.booking_participants enable row level security;
alter table public.payments enable row level security;
